### ISSUE TITLE
logstash output -- elasticsearch block problem

### ISSUE THREAD

**Issue by tomsherrod** [mrlesmithjr/ansible-elk-processor#1]
Fresh pull(as of Friday), logstash out block for elasticsearch:
    elasticsearch {
      host => "fqdn"
      flush_size => 5000
      workers => 2

Which doesn't match the defaults(fqdn:9200) and breaks logstash because hosts => ["fqdn"] is needed(at least it worked after changing).

**Comment by mrlesmithjr** [comment]
for the variables for the logstash_outputs in any var definitions should
look like below. Somewhere in your vars it still is defined as host for
elasticsearch output instead of hosts. I just ran through a fresh install
using the latest code 2 days ago and did not have to modify anything. :)

logstash_outputs:
- output: elasticsearch
  hosts: '{{ logstash_server_fqdn }}:9200'
  protocol: http  #node, transport or http....http is the only protocol
  supported in 2.x+
  flush_size: 5000
  workers: 2

On Wed, Feb 24, 2016 at 4:29 PM, tomsherrod notifications@github.com
wrote:

> Fresh pull(as of Friday), logstash out block for elasticsearch:
> elasticsearch {
> host => "fqdn"
> flush_size => 5000
> workers => 2
> 
> Which doesn't match the defaults(fqdn:9200) and breaks logstash because
> hosts => ["fqdn"] is needed(at least it worked after changing).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mrlesmithjr/ansible-elk-processor/issues/1.

## 

Twitter @mrlesmithjr http://twitter.com/mrlesmithjr
Blog EverythingShouldBeVirtual.com
Interested in blog sponsorship? Go to http://bit.ly/10Aj7Sq

**Comment by tomsherrod** [comment]
Found it:
https://github.com/mrlesmithjr/ansible-elkstack/blob/master/elkstack.yml 
- name: Configure ELK-Processor-Nodes
  hosts: elk-processor-nodes
  remote_user: remote
  become: true
  vars:
  - logstash_outputs:
    - output: elasticsearch
      host: '192.168.202.201'
      protocol: http  #node, transport or http....http is the only protocol supported in 2.x+
      flush_size: 5000
      workers: 2

(spacing hosed up)

**Comment by mrlesmithjr** [comment]
@tomsherrod - Good catch :)

Updated playbook for that.
